# Common Labels
labels:
  app: "message-service"
  group: "core"


ingress:
  enabled: true
  zuul: true
  context: "api/v1/message"
# # Init Containers Configs

# Container Configs
image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/message-service"
  tag: "58e68dad38c33eb22faa9c82ee5731c27e96af3c"
replicas: "1"
# tracing-enabled: true
# healthChecks:
#   enabled: true
#   livenessProbePath: "/management-service/health"
#   readinessProbePath: "/management-service/health"

# Additional Container Envs
env: |
  - name: NOTIFICATIONS_WHATSAPP_DRY_RUN
    value: "true"
  - name: NOTIFICATIONS_SMS_DRY_RUN
    value: "true"
  - name: NOTIFICATIONS_ESCALATION_DRY_RUN
    value: "true"
  - name: NOTIFICATIONS_NUDGE_DRY_RUN
    value: "true"
  - name: JAVA_OPTS
    value: -Xmx192m -Xms192m
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-kraft-controller-headless:9092"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        key: db-url
        name: jalsoochak
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: jalsoochak
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: jalsoochak
  - name: KEYCLOAK_AUTH_SERVER_URL
    value: "http://keycloak:80/keycloak"
  - name: SPRING_MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        key: mail-username
        name: jalsoochak
  - name: SPRING_MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mail-password
        name: jalsoochak
  - name: MAIL_FROM_EMAIL
    valueFrom:
      secretKeyRef:
        key: mail-id
        name: jalsoochak
  - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_DEBUG
    value: "true"
  - name: KEYCLOAK_REALM
    valueFrom:
      secretKeyRef:
        key: keycloak-realm
        name: jalsoochak
  - name: KEYCLOAK_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        key: keycloak-public-key
        name: jalsoochak
  - name: KEYCLOAK_CLIENT_ID
    value: "jalsoochak-app"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: keycloak-credential-secret
        name: jalsoochak
  - name: KEYCLOAK_ISSUER_URI
    valueFrom:
      secretKeyRef:
        key: keycloak-issuer-uri
        name: jalsoochak
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://servicediscovery:8761/eureka"
  - name: GLIFIC_NUDGE_TEMPLATE_ID
    value: "7986"
  - name: GLIFIC_ESCALATION_TEMPLATE_ID
    value: "829817"
  - name: GLIFIC_DAILY_REPORT_SDO_TEMPLATE_ID
    value: "876196"
  - name: GLIFIC_DAILY_REPORT_SO_TEMPLATE_ID
    value: "876193"
  - name: GLIFIC_NUDGE_FLOW_ID
    value: "37300"
  - name: GLIFIC_WELCOME_FLOW_ID
    value: "38949"
  - name: MINIO_ENDPOINT
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: MINIO_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: accessKey
        name: minio
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: secretKey
        name: minio
  - name: MINIO_REGION
    valueFrom:
      secretKeyRef:
        key: region
        name: minio
  - name: MINIO_BUCKET
    value: "escalation-reports"
  - name: MINIO_BASE_URL
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: GLIFIC_API_URL
    value: "https://api.arghyam.glific.com/api"
  - name: GLIFIC_AUTH_URL
    value: "https://api.arghyam.glific.com/api/v1/session"
  - name: GLIFIC_USERNAME
    valueFrom:
      secretKeyRef:
        key: glific-username
        name: glific
  - name: GLIFIC_PASSWORD
    valueFrom:
      secretKeyRef:
        key: glific-password
        name: glific
  - name: GLIFIC_LOGIN_OTP_TEMPLATE_ID
    value: "702101"
  - name: APP_BASE_URL
    value: "https://jalsoochak.beehyv.com"
  - name: MAIL_PROVIDER
    value: "sendgrid"
  - name: MAIL_FROM_NAME
    value: "Jalsoochak"
  - name: MAIL_LOGO_URL
    value: "https://lh3.googleusercontent.com/d/1WUwmfNG_wyWF_G31MaWCtWIsZCxHy5g2"
  - name: SENDGRID_API_KEY
    valueFrom:
      secretKeyRef:
        key: SENDGRID_API_KEY
        name: jalsoochak
  - name: SENDGRID_TEMPLATE_PASSWORD_RESET
    value: "d-f7088f302ac146faa4c165b7539e4cd9"
  - name: SENDGRID_TEMPLATE_REINVITATION
    value: "d-b3e1cb24d3bc40b3b8c3f0c19c8cff79"
  - name: SENDGRID_TEMPLATE_DEFAULT_INVITATION
    value: "d-4f225581b47a4c0ea8e1b84d4be740cb"
  - name: SENDGRID_TEMPLATE_SUPER_USER_INVITATION
    value: "d-c0f4763d5bd948d0879d4bec9e015646"
  - name: SENDGRID_TEMPLATE_STATE_ADMIN_INVITATION
    value: "d-20c14eb80ba84feb87b157f4b1cf4bbc"
  - name: SMSCOUNTRY_DLT_TEMPLATE_ID
    value: "1707177995274127403"
  - name: SMSCOUNTRY_DLT_HEADER_ID
    value: "1705177988665799637" 
  - name: SMSCOUNTRY_SENDER_ID
    value: "JALSHK"
  - name: SMSCOUNTRY_AUTH_KEY
    valueFrom:
      secretKeyRef:
        key: SMSCOUNTRY_AUTH_KEY
        name: jalsoochak
  - name: SMSCOUNTRY_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        key: SMSCOUNTRY_AUTH_TOKEN
        name: jalsoochak
  - name: PII_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        key: pii-encryption-key
        name: jalsoochak
  - name: PII_HMAC_KEY
    valueFrom:
      secretKeyRef:
        key: pii-hmac-key
        name: jalsoochak
  - name: NOTIFICATIONS_DAILY_REPORT_DELIVERY_MODE
    value: "LINK"
  - name: GLIFIC_DAILY_REPORT_SO_LINK_TEMPLATE_ID
    value: "880556"
  - name: GLIFIC_DAILY_REPORT_SDO_LINK_TEMPLATE_ID
    value: "880556" 
  - name: DAILY_REPORT_LINK_BUTTON_BASE_URL
    value: "https://jalsoochak.in/minio/"
