# Common Labels
labels:
  app: "analytics-service"
  group: "core"


ingress:
  enabled: true
  zuul: true
  context: "api/v1/analytics"
# Init Containers Configs

# Container Configs
image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/analytics-service"
  tag: "53ec3ee728c05e8ada1d6d5deaf7e9f92f702669"
replicas: "1"
# tracing-enabled: true
# healthChecks:
#   enabled: true
#   livenessProbePath: "/management-service/health"
#   readinessProbePath: "/management-service/health"

# Additional Container Envs
env: |
  - name: JAVA_OPTS
    value: -Xmx512m -Xms512m
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-kraft-controller-headless:9092"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        key: analytics-db-url
        name: jalsoochak
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: jalsoochak
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: jalsoochak
  - name: KEYCLOAK_AUTH_SERVER_URL
    value: "http://keycloak:80/keycloak"
  - name: SPRING_MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        key: mail-username
        name: jalsoochak
  - name: SPRING_MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mail-password
        name: jalsoochak
  - name: MAIL_FROM_EMAIL
    valueFrom:
      secretKeyRef:
        key: mail-id
        name: jalsoochak
  - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_DEBUG
    value: "true"
  - name: KEYCLOAK_REALM
    valueFrom:
      secretKeyRef:
        key: keycloak-realm
        name: jalsoochak
  - name: KEYCLOAK_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        key: keycloak-public-key
        name: jalsoochak
  - name: KEYCLOAK_CLIENT_ID
    value: "jalsoochak-app"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: keycloak-credential-secret
        name: jalsoochak
  - name: KEYCLOAK_ISSUER_URI
    valueFrom:
      secretKeyRef:
        key: keycloak-issuer-uri
        name: jalsoochak
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://servicediscovery:8761/eureka"
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: "https://jalsoochak.beehyv.com/keycloak/realms/jalsoochak-realm"
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: SPRING_DATA_REDIS_HOST
    value: "redis"
  - name: SINGLE_TENANT_MODE
    value: "false"
  - name: ANALYTICS_DASHBOARD_CACHE_CURRENT_DAY_TTL_SECONDS
    value: "3600"
