# Common Labels
labels:
  app: "apigateway"
  group: "core"


ingress:
  enabled: true
  zuul: true
  contexts:
    - "swagger-ui.html"
    - "swagger-ui"
    - "swagger-resources"
    - "v3/api-docs"
    - "webjars"
    - "user"
    - "tenant"
    - "telemetry"
    - "message"
    - "scheme"
    - "analytics"
    - "api/v1"
# Init Containers Configs

# Container Configs

image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/apigateway"
  tag: "gateway-test-1"
replicas: "1"
# tracing-enabled: true
healthChecks:
  enabled: true
  livenessProbePath: "/actuator/health"
  readinessProbePath: "/actuator/health"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: RATE_LIMIT_ENABLED
    value: "false"
  - name: SPRING_DATA_REDIS_HOST
    value: "redis"
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://servicediscovery:8761/eureka"
  - name: EUREKA_URL
    value: "http://servicediscovery:8761/eureka/"
  - name: EUREKA_ENABLED
    value: "false"
  - name: TENANT_SERVICE_URI
    value: "http://tenant-service:8080"
  - name: USER_SERVICE_URI
    value: "http://user-service:8080"
  - name: ANOMALY_SERVICE_URI
    value: "http://anomaly-service:8080"
  - name: TELEMETRY_SERVICE_URI
    value: "http://telemetry-service:8080"
  - name: MESSAGE_SERVICE_URI
    value: "http://message-service:8080"
  - name: SCHEME_SERVICE_URI
    value: "http://scheme-service:8080"
  - name: ANALYTICS_SERVICE_URI
    value: "http://analytics-service:8080"
  - name: LOG_FILE_PATH
    value: "/var/log/apps/api-gateway.log"
  - name: CORS_ALLOWED_ORIGINS
    value: "*"
  - name: KEYCLOAK_AUTH_SERVER_URL
    value: "http://keycloak:80/keycloak"
  - name: KEYCLOAK_CLIENT_ID
    value: "jalsoochak-app"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: keycloak-credential-secret
        name: jalsoochak
  - name: KEYCLOAK_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        key: keycloak-public-key
        name: jalsoochak
  - name: KEYCLOAK_ISSUER_URI
    valueFrom:
      secretKeyRef:
        key: keycloak-issuer-uri
        name: jalsoochak
