# Common Labels
labels:
  app: "tenant-service"
  group: "core"


ingress:
  enabled: true
  zuul: true
  contexts:
    - "api/v1/tenants"
    - "api/v1/system"
# Init Containers Configs

# Container Configs
image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/tenant-service"
  tag: "b7ff977047c2fc3ee8d74b88da5450fc7bd7864f"
replicas: "1"
# tracing-enabled: true
# healthChecks:
#   enabled: true
#   livenessProbePath: "/management-service/health"
#   readinessProbePath: "/management-service/health"

# Additional Container Envs
env: |
  - name: JAVA_OPTS
    value: -Xmx192m -Xms192m
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-kraft-controller-headless:9092"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        key: db-url
        name: jalsoochak
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: jalsoochak
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: jalsoochak
  - name: KEYCLOAK_AUTH_SERVER_URL
    value: "http://keycloak:80/keycloak"
  - name: SPRING_MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        key: mail-username
        name: jalsoochak
  - name: SPRING_MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mail-password
        name: jalsoochak
  - name: MAIL_FROM_EMAIL
    valueFrom:
      secretKeyRef:
        key: mail-id
        name: jalsoochak
  - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_DEBUG
    value: "true"
  - name: KEYCLOAK_REALM
    valueFrom:
      secretKeyRef:
        key: keycloak-realm
        name: jalsoochak
  - name: KEYCLOAK_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        key: keycloak-public-key
        name: jalsoochak
  - name: KEYCLOAK_CLIENT_ID
    value: "jalsoochak-app"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: keycloak-credential-secret
        name: jalsoochak
  - name: KEYCLOAK_ISSUER_URI
    valueFrom:
      secretKeyRef:
        key: keycloak-issuer-uri
        name: jalsoochak
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://servicediscovery:8761/eureka"
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: SPRING_DATA_REDIS_HOST
    value: "redis"
  - name: STORAGE_ENDPOINT
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: STORAGE_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: accessKey
        name: minio
  - name: STORAGE_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: secretKey
        name: minio
  - name: STORAGE_REGION
    valueFrom:
      secretKeyRef:
        key: region
        name: minio
  - name: STORAGE_BUCKET
    value: "tenant-assets"
  - name: STORAGE_BASE_URL
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: STORAGE_ENABLED
    value: 'true'
  - name: PII_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        key: pii-encryption-key
        name: jalsoochak
  - name: PII_HMAC_KEY
    valueFrom:
      secretKeyRef:
        key: pii-hmac-key
        name: jalsoochak
  - name: SINGLE_TENANT_MODE
    value: "false"
  - name: GLIFIC_RESUME_BASE_URL
    value: "https://api.arghyam.glific.com"
  - name: GLIFIC_RESUME_ENABLED
    value: "true"
  - name: DAILY_REPORT_SCHEDULE_HOUR
    value: "17"
  - name: DAILY_REPORT_SCHEDULE_MINUTE
    value: "00"
