# Common Labels
labels:
  app: "scheme-service"
  group: "core"


ingress:
  enabled: true
  zuul: true
  contexts:
    - "api/v1/public"
    - "api/v1/scheme"
# Init Containers Configs

# Container Configs
image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/scheme-service"
  tag: "d7ea88db4b8b17ed36dbacd6b3dab7b0ad5e1f4c"
replicas: "1"
# tracing-enabled: true
# healthChecks:
#   enabled: true
#   livenessProbePath: "/management-service/health"
#   readinessProbePath: "/management-service/health"

# Additional Container Envs
env: |
  - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
    value: 100MB
  - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
    value: 100MB
  - name: JAVA_OPTS
    value: -Xmx512m -Xms512m
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-kraft-controller-headless:9092"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        key: db-url
        name: jalsoochak
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: jalsoochak
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: jalsoochak
  - name: KEYCLOAK_AUTH_SERVER_URL
    value: "http://keycloak:80/keycloak"
  - name: SPRING_MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        key: mail-username
        name: jalsoochak
  - name: SPRING_MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mail-password
        name: jalsoochak
  - name: MAIL_FROM_EMAIL
    valueFrom:
      secretKeyRef:
        key: mail-id
        name: jalsoochak
  - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_DEBUG
    value: "true"
  - name: KEYCLOAK_REALM
    valueFrom:
      secretKeyRef:
        key: keycloak-realm
        name: jalsoochak
  - name: KEYCLOAK_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        key: keycloak-public-key
        name: jalsoochak
  - name: KEYCLOAK_CLIENT_ID
    value: "jalsoochak-app"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: keycloak-credential-secret
        name: jalsoochak
  - name: KEYCLOAK_ISSUER_URI
    valueFrom:
      secretKeyRef:
        key: keycloak-issuer-uri
        name: jalsoochak
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://servicediscovery:8761/eureka"
  - name: SINGLE_TENANT_MODE
    value: "false"
  - name: MINIO_ENDPOINT
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: MINIO_BUCKET
    valueFrom:
      secretKeyRef:
        key: bucket
        name: minio
  - name: MINIO_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: accessKey
        name: minio
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: secretKey
        name: minio
  - name: MINIO_REGION
    valueFrom:
      secretKeyRef:
        key: region
        name: minio
  - name: STORAGE_PRESIGNED_BASE_URL
    valueFrom:
      secretKeyRef:
        key: presigned-url
        name: minio
  - name: PII_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        key: pii-encryption-key
        name: jalsoochak
  - name: PII_HMAC_KEY
    valueFrom:
      secretKeyRef:
        key: pii-hmac-key
        name: jalsoochak
